### ISSUE TITLE
Dynamické načtení modulů

### ISSUE THREAD

**Issue by pepa-linha** [nittro/core#3]
Ahoj,

bylo by možné načítat dynamicky i JS moduly? 

Pokud je v HTML

```js
window._stack.push({
    load: [
        '/assets/js-module.js'
    ],
```

Tak to skripty načítá podle Content-Type
https://github.com/nittro/core/blob/master/src/context.js#L288

Ale hodilo by se, kdyby byla i podpora pro `type="module"`

Obsah _js-module.js_ je například

```js
import plugin from 'plugin'
console.log('Plugin is prepared')
```

Problém pak ale je, že takový kód se pak vykoná později, než ten kód v HTML, který je na něm závislý. Nestačí zjistit, jestli je soubor načtený, ale zda byl už spuštěný a všechny jeho závislosti (přes `import`y) se načetly. Případně nabízí se nějaké jiné řešení? V případě, že se modul vždy načte později (tím si nejsem jistý?), tak by to nejspíš šlo řešit přes callbacky v kódu.

Díky

**Comment by jahudka** [comment]
Ahoj, tyjo, vůbec nevím, doteď jsem tak nějak žil v tom, že `type="module"` je hudba vzdálený budoucnosti a že to v současnejch prohlížečích nejde použít, Nittro s tím rozhodně nijak nepočítá a neumí s tím pracovat..

Zároveň, jestli se nepletu, tak podpora nativních ES6 modulů by měla implikovat taky podporu `await import(..)`, ne? Takže teoreticky ten Nittro mechanismus pro načítání věcí, který jsou ES6 modul, vůbec nepotřebuješ..?

V každým případě integrovat to do Nittra vypadá jako spíš větší než menší problém a já teď určitě v dohledný době nebudu mít čas to pořešit, takže jestli to potřebuješ a potřebuješ to rychle, zkus prosím udělat PR :heart:

**Comment by pepa-linha** [comment]
Ahoj, díky moc 👍🏼  Vlastně jsi mě tím hodně nakopnul, chtěl jsem v této chvíli co nejméně změn v Latte.

Vyřešil jsem to tak, že stack jsem zatím nechal jsou v nich jen styly. Teprve po načtení stylů se načítají skripty díky `import` a v jeho callbacku teprve probíhá zpracování skriptu.

Tím je to vlastně asi vyřešené 💟 

Pokud na něco narazím, co bych mohl a věděl jak upravit, tak PR udělám :-) Co mě tady u toho napadá, tak že by se mohlo hodit rozšířit `_context` z venku. Teď není možné overridnout žádnou jeho metodu. Ale možná už k tomu není žádný důvod.
